AWSTemplateFormatVersion: '2019-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API de envios

Resources:
  Envios: 
    Type: AWS::Serverless::Function
    Properties: 
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 30
      Events:
        ListPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        CreateEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        Entregado: 
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: put